version: '3.8'
services:
    postgres_db:
        image: postgres:17.4
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: rfhnjirf1997-
            POSTGRES_DB: postgres
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data
        networks:
            - app_network

    spring_app:
        build: .
        depends_on:
            - postgres_db
        environment:
            SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_db:5432/postgres
            SPRING_DATASOURCE_USERNAME: postgres
            SPRING_DATASOURCE_PASSWORD: rfhnjirf1997-
        ports:
            - "8080:8080"
        networks:
            - app_network

volumes:
    postgres_data:

networks:
    app_network:
        driver: bridge